name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE_TO_ASSUME: arn:aws:iam::891612573605:role/github-oidc
  TERRAFORM_VERSION: "1.9.8"

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install Dependencies
        working-directory: web
        run: npm ci

      - name: Build
        working-directory: web
        run: npm run build

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init and Plan
        working-directory: terraform
        run: |
          terraform init
          set +e
          terraform plan -out=tf.plan -detailed-exitcode
          exitcode=$?
          set -e

          if [ "$exitcode" -eq 1 ]; then
            exit 1
          fi

          exit 0

      - name: Show Plan Output
        working-directory: terraform
        run: terraform show tf.plan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tf.plan
          retention-days: 1

      - name: Upload Application Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: web/dist/
          retention-days: 1
